# fly.toml app configuration file generated for coachartie-discord on 2024-07-10T10:33:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coachartie-discord"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  web = "npm run web"
  discord = "npm run start"
