// helpers.js

const {
  createChatCompletion,
  createClaudeCompletion,
  generateAiCompletion,
  generateAiCompletionParams,
  isBreakingMessageChain,
  isExceedingTokenLimit,
  lastUserMessage,
} = require("./helpers-llm.js");

const {
  addUserMessages,
  addUserMemories,
  addRelevantMemories,
  addGeneralMemories,
} = require("./helpers-memory.js");

const {
  assembleMessagePreamble,
  addSystemPrompt,
  addCapabilityPromptIntro,
  addCapabilityManifestMessage,
  convertCapabilityManifestToXML,
  convertMessagesToXML,
  getPromptsFromSupabase,
} = require("./helpers-prompt.js");

const {
  addCurrentDateTime,
  cleanUrlForPuppeteer,
  countMessageTokens,
  countTokens,
  countTokensInMessageArray,
  createTokenLimitWarning,
  destructureArgs,
  displayTypingIndicator,
  doesMessageContainCapability,
  getHexagram,
  getUniqueEmoji,
  parseJSONArg,
  processChunks,
  removeMentionFromMessage,
  sleep,
  splitAndSendMessage,
  splitMessageIntoChunks,
  getConfigFromSupabase,
} = require("./helpers-utility.js");

module.exports = {
  addCurrentDateTime,
  addSystemPrompt,
  assembleMessagePreamble,
  cleanUrlForPuppeteer,
  convertCapabilityManifestToXML,
  convertMessagesToXML,
  countMessageTokens,
  countTokens,
  createChatCompletion,
  countTokensInMessageArray,
  createTokenLimitWarning,
  destructureArgs,
  displayTypingIndicator,
  doesMessageContainCapability,
  generateAiCompletion,
  generateAiCompletionParams,
  getConfigFromSupabase,
  getHexagram,
  getPromptsFromSupabase,
  getUniqueEmoji,
  isBreakingMessageChain,
  isExceedingTokenLimit,
  lastUserMessage,
  parseJSONArg,
  processChunks,
  removeMentionFromMessage,
  sleep,
  splitAndSendMessage,
  splitMessageIntoChunks,
  addUserMessages,
  addUserMemories,
  addRelevantMemories,
  addGeneralMemories,
  createClaudeCompletion,
};
